---
title: "Эффект некогнитивных навыков на результаты молодежи на рынке труда при переходе от учебы к работе"
author: 
  - name: Аванесян Карен Алексеевич
    affiliation: Кафедра управления человеческими ресурсами, Южный федеральный университет
    email: avanesian@sfedu.ru
format: 
  pdf:
    documentclass: article
    toc: true
    toc-depth: 2
    number-sections: true
    latex-engine: xelatex
    mainfont: "Times New Roman"
    lang: ru-RU
  docx:
    toc: true
    geometry: 
      - top=30mm
      - left=30mm
      - right=30mm
  html:
    toc: true
    number-sections: true
lang: ru-RU
citeproc: true
csl: apa-with-abstract.csl
biblio-style: bwl-FU
---

\newpage

## Введение

### Социально-экономический контекст

Переход от подросткового возраста к взрослой жизни сопровождается рядом критически важных выборов в образовании и на рынке труда. По мере того, как молодежь переходит из образовательных учреждений в профессиональную среду и стремится найти достойные рабочие места, их успешная интеграция на рынок труда становится приоритетом для правительств и международных организаций. Примерно с 2015 года вопросы молодежной занятости начали занимать центральное место в глобальной агенде устойчивого развития. Например, в рамках Повестки дня в области Целей устойчивого развития (ЦУР) на период до 2030 года, цель 8 — «Достойная работа и экономический рост», включила задачу 8.6: «Содействие занятости, образованию и обучению молодежи».

Тем не менее, прогресс в этом направлении остается ограниченным. В 2015 году доля молодежи в возрасте 15–24 лет, не занятой ни в образовании, ни на работе, ни в профессиональной подготовке, составляла 21,3%. Данная группа является самой уязвимой в переходе от учебы к работе и обозначается как NEET (Not in education, employment, or training) молодежь. К 2024 году доля NEET-молодежи снизилась лишь незначительно, до 20,4%, причем существенное влияние оказала пандемия COVID-19. Более того, по прогнозам, тренд останется стабильным в 2025 и 2026 годах \[\@ilo2024\]. Это свидетельствует о том, что молодежь по-прежнему сталкивается с дефицитом навыков для полноценного участия в социально-экономической жизни и ограниченным доступом к возможностям на рынке труда.

В дополнение к этому, меняется и спрос на навыки со стороны самого рынка труда. Интенсивная цифровизация и развитие искусственного интеллекта (ИИ) артикулировало акцент на навыках и компетенциях, которые не могут быть полностью или частично заменены автоматизированными решениями и цифровизацией <!--# вставить ссылку на данные Всемирного Экономического Форума -->.

Международная организация труда (МОТ), которая в системе Организации Объединенных Наций (ООН) ответственна за установление международных трудовых стандартов и продвижение глобальной повестки достойного труда, в отчете “Глобальные тенденции занятости молодежи – 2024”, подчеркивает отсутствие значимого прогресса в создании достойных рабочих мест для данной демографической группы. Например, доля молодых людей в возрасте 25–29 лет, занятых низкооплачиваемым трудом, существенно варьируется в зависимости от региона: от 10% в Центральной и Западной Азии до 32% в странах Африки к югу от Сахары, включая 15% в Восточной Европе \[\@ilo2024youth\]. Гарант трудовой деятельности молодежи также значительно различается в зависимости от уровня экономического развития страны: 76% молодых людей в возрасте 25–29 лет в странах с высоким уровнем дохода имеют постоянную оплачиваемую работу, тогда как в странах с низким уровнем дохода этот показатель составляет всего 16%. Кроме того, доля молодежи, занятой временной работой, увеличивается, что отражает тенденцию, которую доклад называет “глобальной к повсеместной казуализации труда”, служащей “источником растущей тревоги среди молодых людей, стремящихся к финансовой независимости и переходу ко взрослой жизни” \[\@ilo2024youth p. xvii\].

В последние годы уязвимость молодежи в контексте трудоустройства была усугублена двумя масштабными событиями: глобальным экономическим кризисом 2009 года и пандемией COVID-19. Исследования показывают, что финансовый кризис значительно осложнил процессы интеграции молодежи в рынок труда по всему миру \[\@tanveerchoudhry2012; \@kelly2015; \@verick2011; \@verd2019; \@montalvao2017\]. Однако пандемия, разразившаяся в 2019 году, усилила вызовы, с которыми сталкивается глобальное сообщество в сфере занятости, и особенно затронула молодёжь. Она «усилила ощущение неопределённости, испытываемое многими молодыми людьми во всем мире, и усложнила выполнение ключевых задач, связанных с переходом во взрослую жизнь, включая отделение от семьи, завершение образования и трудоустройство на полную ставку» \[\@allmang2022\].

Первоначальные оценки указывают на то, что молодёжь пострадала от потери рабочих мест, сокращения рабочих часов и падения доходов в большей степени, чем другие демографические группы \[\@ilo2020youth\]. По оценкам, в результате пандемии в 2020 году глобальный уровень занятости среди молодежи снизился на 8,7 %, тогда как среди взрослого населения этот показатель составил лишь 3,7 % \[\@ilo2021\].

Основная проблема в интеграции молодежи на рынке труда заключается в несоответствии между числом молодых людей, ежегодно выходящих на рынок труда, и потребностями работодателей. Другими словами, предложение труда среди молодежи значительно превышает спрос на него. Эта проблема сохраняется даже в странах с отрицательными демографическими тенденциями вроде низкой рождаемости. Хотя уровень безработицы среди молодежи в мире снижается \[\@ilo2024youth\], этот показатель часто скрывает качественные проблемы. Как отмечено, в значительной части развивающегося мира основная проблема занятости молодежи заключается в низком качестве многих доступных рабочих мест, а не в безработице как таковой; причем большая часть молодежи является самозанятыми или занятыми в домашнем хозяйстве, что часто приносит низкий доход \[\@mckay2018\]. По стандартам МОТ, такая работа не может быть классифицирована как “достойная”.

### Мотивация исследования

Переход от учебы к трудовой деятельности представляет собой важнейший этап в жизни молодежи, сопряжённый с принятием решений, оказывающих значительное влияние на их будущую профессиональную траекторию и жизненные перспективы в целом. Значимость этого этапа подчеркивается его долгосрочными последствиями для социально-экономического положения человека за пределами молодежного возраста: успешное трудоустройство на первую работу, соответствующую уровню квалификации и ожиданиям, создает основу для дальнейшего профессионального роста, тогда как ранняя безработица или неудачный переход в сферу занятости могут иметь продолжительные негативные последствия для трудовой и личной жизни \[\@akkermans2021; \@zacher2021; \@baert2013; \@luijkx2009; \@verbruggen2015\]. Кроме того, эмпирические данные свидетельствуют о том, что связь между высоким уровнем образования и обеспечением постоянной полной занятости является слабее, чем предполагалось; иными словами образование не всегда ведет к высокому уровню удовлетворённости трудовой деятельностью \[\@chesters2020\].

Существует множество подходов к определению понятия «переход от учебы к работе», подробный обзор которых представлен в работе \[\@blokker2023\]. МОТ определяет данный феномен как переход молодых людей (в возрасте от 15 до 29 лет) от завершения обучения к первому официальному или удовлетворяющему виду занятости \[\@ilo2010, с. 4\]. В соответствии с этим подходом, молодежь в возрасте 15–29 лет классифицируется по следующим категориям: (1) переход еще не начался — для тех, кто продолжает обучение либо не учится, но при этом не проявляет активности на рынке труда; (2) в процессе перехода — для тех, кто безработен, занят во временной или неудовлетворительной самозанятости, работает в неоплачиваемом семейном бизнесе либо не учится, но активно ищет работу; (3) завершившие переход — для тех, кто занят по официальному договору на полную занятость, или же в удовлетворительной частичной занятости или в самозанятости. Несмотря на то, что Цели устойчивого развития определяют молодежь как группу в возрасте от 15 до 24 лет, для анализа перехода учеба-работа МОТ расширила верхнюю границу до 29 лет, признавая, что многие молодые мужчины и женщины продолжают обучение до 24 лет, а более широкий возрастной диапазон позволяет точнее учитывать опыт молодежи на рынке труда после окончания учёбы.

Успешность перехода от образования к трудовой деятельности, то есть возможность найти достойную работу, обусловлена совокупностью факторов, включая уровень образования, профессиональную подготовку, а также соотношение спроса и предложения на квалифицированную рабочую силу. Несмотря на то что изначально вопросы занятости и функционирования рынка труда находились в центре внимания экономической науки, анализ академической литературы показывает междисциплинарный характер данной темы, в которой ключевую роль играют психология, социология и экономика \[\@blokker2023\]. Благодаря вкладу различных дисциплин, были выявлены факторы, ранее не принимавшиеся во внимание в рамках традиционных экономических подходов. В частности, всё большее внимание уделяется **некогнитивным навыкам** как важному компоненту успешного перехода от школы к трудовой деятельности \[\@lerman2013; \@glewwe2017; \@zudina2022; \@ripamonti2023; \@avanesian2024\]. Под некогнитивными навыками подразумеваются личностные характеристики, не связанные напрямую с когнитивными способностями, включая мотивацию, самоконтроль, социальные навыки и эмоциональную регуляцию. Исследования всё чаще подчеркивают решающую роль этих навыков в обеспечении успеха на рынке труда, влияя как на возможности трудоустройства, так и на потенциальный уровень дохода — как в развитых \[\@ferguson2011; \@almlund2011a; \@almlund2011\], так и в развивающихся странах \[\@rozhkova2019; \@gimpelson2020\].

### Вопросы исследования

### Степень разработанности проблемы в российской экономической литературе

писать про российскую экономическую науку

### Методология

#### Этап 1 - Трудоустройство - mlm

1\) найти работу

2\) канал найма (формальный или неформальный) - j5.2 [https://docs.iza.org/dp11578.pdfhttps://docs.iza.org/dp11578.pdf](https://docs.iza.org/dp11578.pdf)

3\) horizontal mismatch

4\) overeducation and undereducation (isced maps to icao)

5\) nature of labor - white collar / blue collar job (or introduce 4 categories and run miltinomial logit)

<https://ideas.repec.org/a/ids/ijesbu/v25y2015i2p208-230.html> - entraprenerial

formal or non-formal employment

#### Этап 2 - Кейс НИТ молодежи - transition probability / multi-state models

<https://www.researchgate.net/publication/317192475_Unemployment_persistence_How_important_are_non-cognitive_skills>

<https://cran.r-project.org/web/packages/msm/vignettes/msm-manual.pdf>

#### Этап 3 - Отдача от некогнитивных навыков - lqmm

#### Этап 4 - Удовлетворенность трудом - mlm with ipw, loess regression

### Результаты

Каждый этап исследования должен произвести не менее 3 результатов

### Новизна и вклад исследования

### Апробация исследования и публикации

\newpage

## Обзор литературы

### Некогнитивные навыки: история концептуализации в экономике

Что определяет успех молодежи на рынке труда? Почему одни получают высокую заработную плату, в то время как другие — низкую? Эти вопросы являются фукндаментальными для экономической науки, стремящейся объяснить разброс в индивидуальных экономических результатах через строгие эконометрические модели. Согласно конвенциональному подходу, размер оплаты труда детерминируется в первую очередь уровнем образования и трудовым стажем — такой подход лег в основу так называемого уравнения заработной платы Минсера \[\@mincer1974\]. Несмотря на широкое распространение этой модели в анализе заработной платы, как здравый смысл, так и эмпирические данные указывают на то, что одних лишь образования и опыта недостаточно для объяснения различий в заработной плате. Если бы вся вариация в оплате труда объяснялась через различия в образовании и опыте работы, то все индивиды с одинаковыми годами обучения и стажем получали бы одинаковую зарплату, что явно не соответствует реальности. Экономисты давно признавали наличие других факторов, влияющих на доходы, однако в рамках минсеровской модели такие факторы, как правило, относились к ненаблюдаемым характеристикам и включались в ошибку модели как “ненаблюдаемые способности” \[unobserved abilities\]. Проблема “смещения из-за способностей” \[ability bias\], то есть упущения значимых переменных из уравнения заработной платы, представляет собой серьёзное препятствие для точной оценки отдачи от образования \[\@griliches1977; \@chamberlain1975\]. Кроме того, эти ненаблюдаемые способности, несмотря на их отсутствие в модели, оказываются тесно связанными как с заработной платой, так и с выбором уровня образования, что затрудняет корректную оценку образовательной премии.

На протяжении многих лет экономисты игнорировали ненаблюдаемые способности главным образом из-за трудностей их измерения. Большинство эмпирических исследований измеряли человеческий капитал через простой индикатор — количество лет обучения (educational attainment), не принимая во внимание качество полученных знаний, навыков и способностей. Однако к концу 1980-х и началу 1990-х годов, с ростом доступности данных о когнитивных способностях (благодаря слиянию данных статистических обследований домашних хозяйств с административными образовательными записями и распространению стандартизированных тестов), появилась возможность преодолеть эти эмпирические ограничения \[\@hanushek2008\]. Значительное количество исследований было посвящено оценке влияния когнитивных способностей, часто измеряемых через результаты стандартизованных тестов, на индивидуальные доходы \[\@bishop1989a; \@bishop1989b; \@oneill1990; \@grogger1995; \@neal1996\].

Например, \@blackburn1993 установили, что рост отдачи от образования в США можно объяснить повышенными когнитивными способностями обучающихся. Аналогично, \@hanushek2000 показал, что когнитивные навыки, особенно в области математики и естественных наук, играют более важную роль в производительности труда, чем формальное образование. Эти выводы подчеркнули ограниченность традиционных показателей уровня образования или ресурсов школы в отражении истинного уровня когнитивных способностей, что побудило исследователей включать компонент качества рабочей силы в анализ производительности. Дальнейшие исследования \@murnane2001 подтвердили, что когнитивные навыки, измеренные в старших классах школы, являются сильными предикторами уровня заработной платы спустя десять лет. Однако с учётом роста корреляции между способностями и образованием \[\@herrnstein1994\], \@heckman2001 указывает на трудности разделения эффекта образования и способностей даже при наличии прямых наблюдений последних.

Эти достижения в исследовательской области подтолкнули экономистов к изучению других факторов, определяющих результаты на рынке труда, помимо когнитивных способностей, — прежде всего, черт личности. Возрастающий интерес экономической науки к данной теме был обобщён в понятии **некогнитивных навыков**. В отличие от когнитивных навыков, которые формируются в процессе формального образования и закрепляются посредством получения квалификаций, **некогнитивные навыки**, как правило, не включённые в обязательные образовательные программы, играют ключевую роль в формировании общего человеческого капитала \[Kuzminov et al. 2019\]. Эти характеристики, отражающие индивидуальную гетерогенность и относящиеся к личностным чертам, рассматриваются как навыки, поскольку соответствуют трём основным критериям: (i) продуктивности \[productive\] — то есть способности создавать ценность; (ii) расширяемости \[expandable\] — возможности развития посредством обучения и целевых программ и интервенций \[targeted policies and interventions\]; и (iii) социальности \[social\] — то есть признания ключевой роли социально-экономической среды в процессе их формирования. Эти три критерия лежат в основе так называемого **подхода PES** к общему определению навыков, который представляет собой попытку междисциплинарного синтеза экономических, психологических и социологических подходов к данной проблематике \[\@green2013\]. Таким образом, **некогнитивные навыки** определяются как устойчивые паттерны мышления, эмоций и поведения \[Borghans et al. 2008\], формирующиеся в контексте социально-экономической среды, поддающиеся развитию с помощью обучающих программ и целевых интервенций, и способные приносить как экономическую, так и социальную ценность \[Zhou 2016\].

Такие навыки также обозначаются как социально-эмоциональные навыки, мягкие навыки или навыки XXI века, и чаще всего измеряются с использованием модели «Большой пятерки» личностных черт: открытость опыту, добросовестность, экстраверсия, дружелюбие и нейротизм (или эмоциональная стабильность). Однако в практическом смысле термин “некогнитивные навыки” используется экономистами как собирательное понятие для обозначения всего, что не охватывается когнитивными тестами (навыки чтения, счёта и т.п.) \[\@gutman2016\]. Это могут быть такие качества, как самоконтроль, целеустремлённость, мотивация и т.д. С экономической точки зрения эти навыки рассматриваются как вторая, наряду с когнитивной, ключевая ось индивидуальной гетерогенности, определяющей жизненный успех \[\@humphries2017\].

Первое значимое упоминание некогнитивных навыков в контексте экономических результатов было сделано марксистскими экономистами \@bowles1976 в их фундаментальной работе *Schooling in Capitalist America*. Они утверждали, что такие черты, как мотивация, дисциплина и интериоризация социальных норм, играют важную роль в воспроизводстве социального неравенства и доступа к рабочим местам. Хотя формальное образование вознаграждает высокий IQ, авторы подчеркивали, что межпоколенческая передача социально-экономического статуса осуществляется во многом через некогнитивные механизмы. Аналогичным образом, в классической работе по экономике образования *Who Gets Ahead?* \@jencks1979 показал, что такие личностные черты, как усердие, настойчивость и лидерские качества, значимо влияют на уровень дохода — зачастую не менее, чем образование, IQ и социально-экономический статус родителей.

Несмотря на эти ранние результаты исследований, экономическая значимость личностных характеристик оставалась слабо изученной, поскольку исследование личности в основном находилось в фокусе психологии или социологии. Спустя 26 лет после публикации своей первой книги, \@bowles2002 вновь обратились к данной теме, подчеркнув, что межпоколенческая передача экономического статуса обусловлена множеством факторов: от генетической и культурной передачи когнитивных и некогнитивных способностей до наследования богатства и социального капитала (включая принадлежность к этническим или социальным группам), а также преимуществ в области образования и здоровья, присущих детям из семей с высоким статусом. При этом авторы отмечают, что, в отличие от образования и когнитивных навыков, такие факторы, как богатство, раса и некогнитивные черты, оставались вне должного внимания научного сообщества.

Лишь с середины 2000-х годов экономисты начали напрямую учитывать личностные характеристики в анализе факторов, определяющих заработную плату. В пионерском исследовании \@heckman2006 было показано, что влияние некогнитивных навыков на многие тндивидуальные результаты на рынке труда сравнимо, а порой и превосходит влияние когнитивных. Более того, некогнитивные навыки влияют на заработную плату как напрямую — через повышение производительности труда, так и косвенно — через влияние на образовательные траектории и накопление опыта. Эти выводы в определённой степени подтверждают более ранние гипотезы \@bowles1976, согласно которым ценности, которые работодатели ищут в работниках, соответствуют тем, которые педагоги поощряют в учениках. <!--# рассказать про Перри пре скул программу -->

Таким образом, когнитивные навыки, некогнитивные навыки, уровень образования и профессиональная занятость, наряду с социально-экономическим статусом, образуют сложную систему факторов, через которую воспроизводится социальное и экономическое неравенство. Особенно важную роль играют некогнитивные навыки, поскольку они определяют как образовательные, так и профессиональные выборы индивидов, тем самым опосредованно влияя на их доходы \[\@roberts2007\]. Например, лица с высоким уровнем экстраверсии чаще выбирают лидерские роли, а с высокой доброжелательностью — успешно работают в командах. Некогнитивные характеристики также влияют на рынок труда через механизмы найма: соискатели с высокой экстраверсией и добросовестностью и низким уровнем нейротизма воспринимаются работодателями более позитивно, что повышает их шансы на успешное трудоустройство.

### Что такое некогнитивные навыки? Проблема таксономии

Несмотря на широкую популярность термина «некогнитивные навыки» в экономической литературе, он подвергается критике в ряде других дисциплин, включая психологию — область знания, из которой исторически возник. Как отмечается в ряде работ, на фоне относительно ясного представления о том, что собой представляют когнитивные навыки, попытки определить, какие именно навыки относятся к некогнитивным, оказываются гораздо более сложными и противоречивыми \[Cabus et al. 2021\]. Наиболее распространённый подход к определению некогнитивных навыков через исключение, то есть через объяснение их тем, чем они не являются (так называемый «exclusion approach») \[Messick 1978, с. 2\], подвергается обоснованной критике как создающий ложную дихотомию \[false dichotomy\] между когнитивным и некогнитивным характеристиками личности \[Farrington et al. 2012; Duckworth & Yeager 2015\]. Такой подход искусственно исключает когнитивные механизмы из анализа личностных характеристик, которые на деле могут включать как когнитивные, так и некогнитивные аспекты.

В связи с этим, как было упромянто выше, в современной литературе встречается ряд альтернативных теринов: социально-эмоциональные навыки, навыки будущего, трансверсальные навыки, мягкие навыки \[soft skills\] и многие другие.

В научной литературе некогнитивные навыки так-же известны как социально-эмоциональные навыки \[Attanasio et al., 2020; Zhou, 2017\], навыки XXI столетия2, трансверсальные навыки \[Cinque, Carretero, Napierala, 2021\], или soft skills, так называемые мягкие навыки \[Koch, Nafziger, Nielsen, 2015; Laker, Powell, 2011\].

Рассказать больше про упомянутые выше альтернативные определения - социально-эмоциональные навыки как самое распространенное, навыки будушего в таксоногмии всемирного экономического форума, а также трансверсальные навыки или мягкие навыки

Попытка интер-претировать Большую пятерку в категориях, более актуальных в контексте накопления человеческого капитала в системе школьного образования, привела к созданию новой таксономии, разработанной ОЭСР в рамках Исследования социаль-но-эмоциональных навыков (Study on Social and Emotional Skills \[SSES\]). Она включает 15 навыков, которые составляют пятифак-торную модель и измеряются у 10- и 15-летних школьников."

все эти определения могут разниться в деталях но их объединяет одно - акцент на универсальном характере этих навыков, который не привязан к конкретной профессии и выступают универсальными критериями успеха

Second difficulty in using this concept is related to the taxonomy of non-cognitive skills, a question that still remains open and even debatable in the academic community. Since scholars in their research on non-cognitive skills use quite different characteristics to measure their impact on a person’s social or economic outcomes, the confusion about the nature of these skills may seriously hinder the universality of statistical conclusions and analysis in this field. Despite all the open questions and unresolved contradictions in the conceptualization of non-cognitive skills, the most common approach to their taxonomy refers to the 5-factor model of personality, also known as the “Big Five” (BFI) personality traits. This model includes traits such as extraversion, neuroticism, conscientiousness, openness to new experience, and agreeableness ([**Goldberg 1992**](https://www.mdpi.com/2227-7099/12/1/25#B33-economies-12-00025)). The model emerged in response to the need for scientific classification of personality and its fundamental components. Despite the wide representation in science of multifactorial personality models—predecessors of the Big Five, such as H. Eysenck’s 3-factor model of personality and R. Cattell’s 16-factor model, as well as a number of other classifications ([**Almagor et al. 1995**](https://www.mdpi.com/2227-7099/12/1/25#B2-economies-12-00025); [**De Raad and Szirmak 1994**](https://www.mdpi.com/2227-7099/12/1/25#B21-economies-12-00025); [**Benet-Martínez and Waller 1997**](https://www.mdpi.com/2227-7099/12/1/25#B9-economies-12-00025); [**Di Blas and Forzi 1999**](https://www.mdpi.com/2227-7099/12/1/25#B24-economies-12-00025); [**Lee and Ashton 2006**](https://www.mdpi.com/2227-7099/12/1/25#B47-economies-12-00025))—the Big Five is currently the most popular and is spreading in other disciplines studying human behavior. Early psychometric measurements demonstrated the orthogonal nature of the traits proposed by this model, i.e., the absence of mutual correlation between the factors that explain the five key sources of variation in a series of descriptive characteristics of personality in different languages ([**Saucier and Goldberg 2002**](https://www.mdpi.com/2227-7099/12/1/25#B63-economies-12-00025)). Although subsequent research ([**Hussey and Hughes 2020**](https://www.mdpi.com/2227-7099/12/1/25#B41-economies-12-00025); [**Viswesvaran and Ones 2000**](https://www.mdpi.com/2227-7099/12/1/25#B75-economies-12-00025)) questioned the complete independence of the five factors, the psychometric characteristics of this model still surpass the others, explaining its popularity in psychology and other behavioral sciences.

Although initially the specified characteristics were interpreted as personality traits, recent literature rather interprets them as skills, since these characteristics, on the one hand, are instrumental (i.e., produce value and have a return on the labor market), and on the other hand, can be developed through targeted interventions, especially at an early age ([**Heckman et al. 2011**](https://www.mdpi.com/2227-7099/12/1/25#B38-economies-12-00025)).

"Экономические исследования показали, что наиболее эффективны программы формирования некогнитивных навыков, проводимые в раннем детстве, на стадии дошкольного образования \[Heckman, 2006; Almlundetal., 2011\]. Эконометрический анализ подтвердил, что отдача от инвестиций в развитие некогнитивных навыков тем выше, чем раньше они проводятся, особенно в отношении стимулирования достижений представителей бедных слоев населения \[Heckman, 2000\]. С помощью программ социально-эмоционального обучения удалось улучшить академические достижения детей из беднейших семей, и лонгитюдные замеры подтвердили восходящую социальную мобильность участников этих программ \[Knudsenetal., 2006\]. Как следствие, в научный обиход вошло утверждение «навыки порождают навыки», закрепившее взаимосвязь когнитивных и некогнитивных характеристик."

### Некогнитивные навыки в переходе "учеба-работа": эффект на результаты на рынке труда

Эмпирические данные свидетельствуют о значительном влиянии личностных черт, измеренных с использованием модели «Большой пятерки», на благополучие молодежи в период перехода от завершения обучения к вхождению в мир труда [@buhl2007]. Так, результаты исследования, основанного на лонгитюдных данных о выпускниках профессиональных образовательных учреждений, показали, что экстраверсия и эмоциональная стабильность связаны с более успешным поиском работы после окончания учёбы, а также что отдельные взаимосвязи между чертами личности и результатами поиска работы опосредованы уровнем социального капитала, то есть ресурсами, доступными через социальные связи [@baay2014, с. 739].

В одном из масштабных исследований, охватившем период жизни участников от раннего детства до выхода на пенсию, оценивалось влияние личностных черт на внутренний (удовлетворенность работой) и внешний карьерный успех (статус профессии и доход) [@judge1999]. Было установлено, что добросовестность (conscientiousness) положительно коррелирует как с внутренними, так и с внешними показателями карьерного успеха, тогда как нейротизм (neuroticism) негативно влияет на внешний успех. В целом, при контроле общего уровня когнитивных способностей, исследование показало, что даже личностные характеристики, измеренные в раннем возрасте, объясняют значительную долю вариации в карьерных результатах.

В другом исследовании, основанном на данных Немецкой социально-экономической панели (SOEP), была оценена связь между личностными чертами и продолжительностью безработицы. Результаты показали, что такие черты, как добросовестность и нейротизм, оказывают значительное влияние на вероятность трудоустройства в конкретный момент времени: первая увеличивает эту вероятность, а вторая — снижает [@uysal2011].

Несколько исследований были посвящены изучению роли некогнитивных навыков, измеренных с использованием большой пятерки, в отношении молодежи, находящейся вне системы образования, занятости и обучения (NEET) — наиболее уязвимой группы в процессе перехода от школы к трудовой деятельности. Анализ, основанный на данных Российского мониторинга экономического положения и здоровья населения (RLMS-HSE), дал последовательные результаты, указывающие на отрицательную связь между добросовестностью и статусом NEET, а также на положительную связь между нейротизмом и этим статусом [@avanesian2024; @zudina2022].

Другая важная линия исследований выходит за рамки модели «Большой пятерки» и анализирует влияние некогнитивных навыков на переход от школы к работе. Широкий круг работ подчёркивает особую роль самоэффективности (self-efficacy) в этом процессе [@lent1999; @emirza2021; @tolentino2018; @masdonati2021; @grosemans2018]. Хотя самоэффективность нередко в академической литературе связываается с таким аспектом большой пятерки, как добросовестность, оригинальная концепция была предложена психологом А. Бандурой в рамках теории социального научения. Данное понятие определяется как механизм личностного агентства, то есть убеждённость в собственной способности организовать и реализовать действия, необходимые для управления будущими ситуациями [@self-eff1995, с. 2]. Проще говоря, самоэффективность отражает личную веру человека в возможность достижения поставленной цели или выполнения конкретной задачи. В этом контексте убежденность в успехе трудоустройства не гарантирует получение работы, однако она способствует формированию поведенческих стратегий, действий и установок, которые, в конечном итоге, увеличивают вероятность достижения данной цели. В этом смысле данная характеристика схожа с другим понятием из психологии — локусом контроля, так как обе категории выражают личностную агентность. Локус контроля определяется как степень, в которой индивид считает, что контролирует события собственной жизни, в противоположность вере в влияние внешних факторов. <!--# посмотреть есть ли исследования локуса контроля на трудоустройство -->Эта характеристика может в определённой мере компенсировать социально-экономическое неблагополучие, способствуя снижению риска бездействия и безработицы. Однако данные показывают, что она не обеспечивает устойчивую защиту от долгосрочной экономической неактивности, особенно если молодой человек на протяжении более шести месяцев не был занят в образовании, занятости или обучении [@ng-knight2017].

[Non-cognitive skills and labour market performance of immigrants](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0281048) - статья про вероятность трудоустройства мигрантов и рольт некогнитивных навыков

### Экономическая отдача от некогнитивных навыков на рынке труда

The economic literature emphasizes the influence of non-cognitive skills on wages in different countries and socio-economic contexts. It was proven that the return on non-cognitive skills in developed countries increased over time from 1993 to 2013, whereas the effect of cognitive abilities began to decline from 2000. Moreover, it was highlighted that the return on non-cognitive skills exceeds the return on cognitive ones ([**Edin et al. 2022**](https://www.mdpi.com/2227-7099/12/1/25#B26-economies-12-00025)). Measurements in developing countries also confirmed that non-cognitive skills largely explain earnings ([**Perez 2020**](https://www.mdpi.com/2227-7099/12/1/25#B55-economies-12-00025)). For example, special attention in this context was paid to traits such as conscientiousness and extraversion ([**Nyhus and Pons 2005**](https://www.mdpi.com/2227-7099/12/1/25#B54-economies-12-00025)); on the other hand, neuroticism and agreeableness usually have a negative impact on earnings ([**Fletcher 2013**](https://www.mdpi.com/2227-7099/12/1/25#B30-economies-12-00025)).

### Некогнитивные навыки и удовлетворенность трудом

\newpage

## Данные

Данные по 15-29

характеристика выборки (пол, возраст, тип поселения, уровень образования, учится сейчас , статус занятости

Описательные статистики по некогнитивным навыкам

Таблица единичных утверждений

Матрица корреляций некогнитивных навыков

Альфа Кронбаха

\newpage

## Путь от учебы к работе: способствуют ли некогнитивные навыки трудоустройству молодежи?

-   трудоустройство (модель должна смотреть на лагированный статус на рынке труда год или два назад)

    хотя сам факт трудоустройства важен но чтобы понять глубину роли некогнитивных навыков на трудоустройство, необходимо принимать во внимание другие качественные характеристики трудоустройствыа- соответствуют ли они образованию индивида, уровню его компетенций и навыков, характеру труда. Также важную роль играет понимание каналов найма которые использует индивид

-   характер труда <https://www.eurofound.europa.eu/en/coding-and-classification-standards-0>

-   канал найма

-   трудовой мисматч (горизонтальный, пере-образование) -important in the context of decent employment <https://www.emerald.com/insight/content/doi/10.1108/ijm-10-2023-0611/full/html>

    <https://vo.hse.ru/article/view/15663>

    <https://www.sciencedirect.com/science/article/abs/pii/S0272775720305197?via%3Dihub>

\newpage

## Кейс NEET-молодежи: могут ли некогнитивные навыки помочь?

Описательный график для профиля - возраст на оси х и на оси у два шарика - 2016 т 2019 год с долей молодежи НИТ

Смысл в том что в возрастной когорте 15-24 коэффициент скорее будет указывать на выпадение из системы образования

Четыре статуса - нит безработные, нит-неактивные, учатся, работают

<https://www.tandfonline.com/doi/full/10.1080/02673843.2024.2306256#d1e163>

<https://www.tandfonline.com/doi/full/10.1080/02673843.2024.2331576#d1e142>

\newpage

## Отдача от некогнитивных навыков: насколько она гетерогенна в зависимости от уровня оплаты труда?

### Постановка проблемы

### Результаты

### Дискуссия

### Заключение

\newpage

## Эффект некогнитивных навыков на удовлетворенность работой: варьируется ли он в зависимости от уровня заработной платы?

\newpage

## Заключение

говорить о том как таксономия имеет ограничения с точки зрения применения в гос регулировании - этический компонент

потенциал для будущих исследований некогнитивных навыков и молодежи
